[build]
  builder = "nixpacks"
  buildCommand = "npx prisma generate && npm run build"
  startCommand = "npm start"

[deploy]
  healthcheckPath = "/api/auth/session"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3

[[services]]
  name = "web"
  source = "."

[[services]]
  name = "queue-worker"
  source = "."
  startCommand = "npm run queue:worker"
